server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/promtail-positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: laravel-opentelemetry
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravel-opentelemetry
          __path__: /var/www/storage/logs/**/*.log # recursive
